name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}      

    - name: Build the Docker image
      run: docker build -t expresstest .

    - name: taging
      run: docker tag expresstest:latest jjang6251/expresstest:latest

    - name: Push to Dockerhub
      run: docker push jjang6251/expresstest:latest
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
    - name: Deploy to Server
      env:
        HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.HOST_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts
        
        sshpass -p "$HOST_PASSWORD" ssh -o StrictHostKeyChecking=no user@${{ secrets.HOST_IP }} << EOF
          # Docker 컨테이너 중지 및 제거
          docker stop my-express-app || true
          docker rm my-express-app || true
          
          # 최신 이미지 Pull
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/expresstest:latest
          
          # 컨테이너 실행
          docker run -d \
            --name expresstest \
            -p 3000:8000 \
            ${{ secrets.DOCKERHUB_USERNAME }}/expresstest:latest
        EOF