name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}      

    - name: Build the Docker image
      run: docker build -t expresstest .

    - name: taging
      run: docker tag expresstest:latest jjang6251/expresstest:latest

    - name: Push to Dockerhub
      run: docker push jjang6251/expresstest:latest
    
  deploy:

    runs-on: self-hosted
    needs: build

    steps:
    - name: Pull Docker image
      run: sudo docker pull jjang6251/expresstest:latest
    - name: Delete Old docker container
      run: sudo docker rm -f expresstest-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:8000 --name expresstest-container jjang6251/expresstest